openapi: 3.1.0

info:
  version: 1.0.0
  title: Excursions API
  description: |
      Documentation of all Excursions API Server endpoints. A lightweight group travel planning app focused on the United States National Parks.

  license:
    name: GNU Affero General Public License
    url: https://www.gnu.org/licenses/agpl-3.0.en.html

# servers:
#   - url: 'none'

components:
  securitySchemes:
    bearerToken:
      $ref: './components/securitySchemas/common/tokens/bearerToken.yaml'

tags:
  - name: User Management
    description:

  - name: User Authentication
    description:

x-tagGroups:
  - name: Users
    tags:
      - User Management
      - User Authentication

paths:
  "/user":
    $ref: './paths/user.yaml'
  "/users":
    $ref: './paths/users.yaml'
  "/user/{userId}":
    $ref: './paths/user_{userId}.yaml'
  "/user/sign-in":
    $ref: './paths/user_sign-in.yaml'
  "/user/sign-out":
    $ref: './paths/user_sign-out.yaml'
