openapi: 3.1.0

info:
  version: 0.0.0
  title: Example API
  description: |
      A template to build OpenAPI documentation from.

  license:
    name: none
    identifier: none

servers:
  - url: 'none'

components:
  securitySchemas:
    BearerToken:
      $ref: './components/securitySchemas/common/tokens/bearerToken.yaml'

tags:
  - name: User Management
    description: 

  - name: User Authentication
    description: 

x-tagGroups:
  - name: Users
    tags:
      - User Management
      - User Authentication

# paths:
